### PR TITLE
Update JagdPz_E100.json

### PR DESCRIPTION
**Pull request by modderforyou**
healt 2200 purchase free level 0 sell 9999999999999999999999999999999999999

### CODE REVIEW

**Comment by modderforyou** [comment]
why closed give idea please

**Comment by modderforyou** [comment]
for open source = test no coin rush jg pz e100 real pv in wot 2200 and free purchase and sell infinite coin for buy other tank

**Comment by modderforyou** [comment]
please authored me jg pz e100 just for fun no for online

**Comment by Doreamonsky** [comment]
.json files are useless now.
We don‘t have such purchase and level system now.

If u want to contribute to this project，u should try adding tanks and maps

**Comment by Doreamonsky** [comment]
Files in others folder are temporary and useless files
cache during the editing

**Comment by modderforyou** [comment]
I do not understand the other function I come to dariver on the site today and I saw that I am a fan of the game so I wanted to contribute but I do not understand too much or are the files if you can help it would be cool

**Comment by Doreamonsky** [comment]
u can follow the https://github.com/Doreamonsky/PanzerWar/blob/master/README.md
to run the game in the editor and add vehicles as videos do

**Comment by modderforyou** [comment]
Ok

**Comment by modderforyou** [comment]
Plz for next update ad maus and jg pz e100 and fv 215 b 183

**Pull request closed without merging**
